export const FETCH_DATA_START= 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS= ' FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';

export const ADD_OPTION = 'ADD_OPTION';
export const ADD_OPTION_FAIL = 'ADD_OPTION_FAIL';

export const ADD_PRODUCT = 'ADD_PRODUCT';

export const CANCEL_ORDER = 'CANCEL_ORDER';
export const REMOVE_ORDER = 'REMOVE_ORDER';
export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS';
export const SEND_ORDER_FAIL = 'SEND_ORDER_FAIL';
export const SEND_ORDER_START = 'SEND_ORDER_START';
export const FETCH_ORDERS_START= 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS= ' FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const FETCH_USER_START= 'FETCH_USER_START';
export const FETCH_USER_SUCCESS= ' FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';
