export const FETCH_PRODUCTS_START= 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS= ' FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';

export const FETCH_CATEGORIES_START= 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS= ' FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';

export const FETCH_SAUCES_START= 'FETCH_SAUCES_START';
export const FETCH_SAUCES_SUCCESS= ' FETCH_SAUCES_SUCCESS';
export const FETCH_SAUCES_FAIL = 'FETCH_SAUCES_FAIL';