export const FETCH_DATA_START= 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS= ' FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';

export const ADD_OPTION = 'ADD_OPTION';
export const ADD_OPTION_FAIL = 'ADD_OPTION_FAIL';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const REMOVE_ORDER = 'REMOVE_ORDER';
